<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	ComproPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) ComproPago [http://www.compropago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>


<?php 

if ($this->getAllowed() == 1){
if ($this->getCountry() == 'MLB'){?>
<img id ="mpbt"src="<?php echo $this->getimgcheckoutBr()  ;?>" alt="<?php echo Mage::helper('compropago')->__('Comprar Agora com ComproPago');?>" title="<?php echo Mage::helper('compropago')->__('A compra será realizada em uma janela de segurança do ComproPago');?>" />
<span style="line-height:3.3; padding-left:2px;padding-right:2px;"><b><?php echo $this->__('Ou');?></b></span>
<?php }else{ ?>
<a href="<?php echo $this->getcheckoutfaster()  ?>"><img src="<?php echo $this->getimgcheckoutAr()  ;?>" alt="<?php echo Mage::helper('compropago')->__('Comprar Agora con ComproPago');?>" title="<?php echo Mage::helper('compropago')->__('Comprar Agora con ComproPago');?>" /></a>
<span style="line-height:3.3; padding-left:2px;padding-right:2px;"><b><?php echo $this->__('O');?></b></span>    
<?php };?>
<?php } ;?>


<script src="<?php echo $this->getJsUrl('chico/chico-0.11.js'); ?>"></script>
<script type="text/javascript">
    var $j = jQuery.noConflict(); 

    // $j("#example").tooltip();
    var foo = $j("#mpbt").modal({
    "content": "<iframe id='mpmodal' src='<?php echo $this->getcheckoutfaster()  ?>' style='width: 780px; height: 520px' />",
    "width": "800px",
    "height": "540px"
    });
    

    var tip = $j("#mpbt").tooltip();
</script>


