<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	ComproPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) ComproPago [http://www.compropago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/compag/modal.css'); ?>" />
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/compag/livepipe.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/compag/window.js'); ?>"></script>