<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	ComproPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) ComproPago [http://www.compropago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="close-white">
<a class="ch-close" onclick="closeRender();" style="z-index: 1002;">×</a>
</div>
<center><iframe id="CP-Checkout-IFrame" frameborder="0" style="width: 740px; height: 480px;" src="<?php echo ($this->getPreference()) ?>"></iframe></center>

<script type="text/javascript">

 $j(document).ready(function() {
     checkoutsize();
});

</script>