<?php

/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   	Payment Gateway
 * @package    	ComproPago
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) ComproPago [http://www.compropago.com]
 * @license    	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<fieldset class="form-list">
    <?php  $_code=$this->getMethodCode(); ?>
    <?php $_country = $this->getMethodCountry(); ?>

<ul id="payment_form_<?php  echo $_code ?>" >       
       <?php if($this->getMethod()->getConfigData('acc_origin') == 'MX'): ?>  
       <label for="p_method_cpfaster" style="cursor:pointer;">
	       <li>
	       <img src="<?php echo $this->getSkinUrl('images/cpfaster/compropago-mx.png'); ?>" alt="ComproPago" title="ComproPago" />
	       </li>
	   </label>
      <?php endif; ?> 
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>





